# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ua-CD3MrEaBustnkLxPdV4lpk1FqsRza
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings as wr
wr.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
d=pd.read_csv('/content/winequality-red (1).csv')
df=pd.DataFrame(d)
df.head()
df.info()
#Null places are identified and dropped
df.fillna(0,inplace=True)
df.isnull().sum()
#Identifying the outliers
Q1=df.quantile(0.25)
Q3=df.quantile(0.75)
IQR=Q3-Q1
outliers=((df<(Q1-1.5*IQR))|(df>(Q3+1.5*IQR))).sum()
print(outliers)
x=df.iloc[:,:-1]
y=df.iloc[:,-1:]
print(x)
print(y)
# for i in range(len(y)):
#   if(y[i]==7 or y[i]==8):
#     y[i]=1
#   else:
#     y[i]=0
#   print(y[i])
print("No categorical columns")
df.drop_duplicates(inplace=True)
print("duplicate entries were dropped")
clf=RandomForestClassifier()
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = .2)
print("splitting was done")
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
print(pred)
print("Model was developed")
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(pred,y_test)
print('accuracy=',accuracy)