# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWe6c3Zqo9kWZnlChlmudQaMJGLAtkh9
"""

import pandas as pd
from sklearn.ensemble import IsolationForest
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
data=pd.read_csv('/content/social_network.csv')
df=pd.DataFrame(data)
X=df.iloc[:,:-1]
y=df.iloc[:,-1:]
clf=clf.IsolationForest()
clf.fit(X)
y_pred = clf.predict(X)
df["anomalyscore"] = clf.decision_function(X)
anomalies = df.loc[df["anomalyscore"] < 0]
df_test= pd.read_csv("/content/social_network.csv")
x=df_test[["login_activity", "social_connections","posting_activity"]]
df_values=x.values

find=df_values

result=[]
for i in find:
  j=clf.predict([i])
  if j==[1]:
    result.append('Not an Anomaly')
  elif j==[-1]:
    result.append('Anomaly')

df_test['Anomaly']=result
print(df_test)
plt.scatter(df["social_connections"], df["anomaly_score"], label="Not Anomaly")
plt.scatter(anomalies["social_connections"], anomalies["anomalyscore"], color="r", label="Anomaly")
plt.xlabel("Social Connections")
plt.ylabel("anomalyscore")
plt.show()