# -*- coding: utf-8 -*-
"""LVADSUSR@122-SRILASYA-IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pInNewbWd-m9AD9u0GnDgZ0cHNwL1tzB
"""

#1
import numpy as np
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],[[255,255,0],[255,0,255],[0,255,255]],[[127,127,127],[200,200,200],[50,50,50]]])
print(rgb_image)
rgb_image_1=[]
sum=0
for i in rgb_image:
  for j in i:
    for k in j:
      if k%3==1:
        rgb_image_1[i,j,k]=rgb_image[i,j,k]*0.2989
      elif k%3==2:
        rgb_image_1[i,j,k]=rgb_image[i,j,k]*0.581
      elif k%3==0:
       rgb_image_1[i,j,k]=rgb_image[i,j,k]*0.1140
    sum+=rgb_image_1[i,j,k]
print(sum)

#2
students=np.array([[20,25,23],[23,24,25],[20,'exempt',22]])
print(students)
sum=0

#3
print("data from multiple sensors(i considered  3 sensors)")
sensors=np.array([[[500,600],[300,400]],[[900,800],[200,100]],[[50,150],[250,350]]])
# printed as 3d array with information
print(sensors)
#reshaped it as such as it is flattened into a single row for each sensor
a=sensors.reshape(3,4)
print("Information of each sensor in a single row without changing order of elements")
print(a)

#4
athletes=np.array([[20,18,19],[22,19,19],[18,18,19]])
print(athletes)
# b=(a,index=(['game1','game2','game3']),column=('atlete1','atlete2''atlete3'))
c=[]
for i in athletes:
  for j in i:
   c[j]=athletes[i[-1]]-athletes[i[0]]
   if c[j]>0:
    print('athlete is improved')
   if c[j]==0:
    print('no change in performance')
   if c[j]<0:
    print('performance was not well')

#5
students=np.array([[20,25,23],[23,24,25],[20,'exempt',22]])
print(students)
sum=0
for i in students:
  for j in i:
    if j=='exempt':
      j=-1
  sum+=j
 mean[i]=sum/len(students)
print(mean[i])

#6
temps=np.array([[20,30,25],[33,22,25],[40,35,30]])
a=(temps,index=['h','b','c'],column=['jan','feb','mar'])
print(temps)

#7
students=np.array([[20,25,23],[23,24,25],[20,'exempt',22]])
print(students)
sum=0

#8
athletes=np.array([[20,18,19],[22,19,19],[18,18,19]])
print(athletes)
# b=(a,index=(['game1','game2','game3']),column=('atlete1','atlete2''atlete3'))
c=[]

#9
import numpy as np
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],[[255,255,0],[255,0,255],[0,255,255]],[[127,127,127],[200,200,200],[50,50,50]]])
print(rgb_image)

#10
print("data from multiple sensors(i considered  3 sensors)")
sensors=np.array([[[500,600],[300,400]],[[900,800],[200,100]],[[50,150],[250,350]]])
# printed as 3d array with information
print(sensors)
#reshaped it as such as it is flattened into a single row for each sensor
a=sensors.reshape(3,4)
print("Information of each sensor in a single row without changing order of elements")
print(a)