# -*- coding: utf-8 -*-
"""LVADSUSR@122.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L76ryGDqmzrGRPGshD05ufBLxNonNWjY
"""

#1
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv('/content/Walmart_Dataset Python_Final_Assessment (1).csv')
df=pd.DataFrame(data)
print(df.info())
print('Describing the basic factors in data')
print(df.describe())
print('no.of rows')
a=df.len(df.axes[0])
print(a)
print('no.of columns')
b=df.len([df.axes[1]])
print(b)
numerical_coloumns=df.columns[df.Dtype!="object"]
print(numerical_coloumns)
categorical_columns=df.columns[df.dtype=="object"]
print(categorical_columns)
print('No.of Null values')
null_values=df.isnull.sum()
print(null_values)

#2
print('Handling missing values')
print('Dropping Null Values')
drp_null=df.dropna(inplace=True)
print(drp_null)
print('Identifying duplicate data entries')
df.drop_duplicates()
print('Duplicates were identified and droped')
print('Duplicates are resolved')

#3
print('Analysing the measures of data')
print('Mean of the given data')
Meana=df["Sales"].mean()
Meanb=df["Quantity"].mean()
Meanc=df["Profit"].mean()
print(Meana)
print(Meanb)
print(Meanc)
print('Median of the given data')
mediana=df["Sales"].median()
medianb=df["Quantity"].median()
medianc=df["Profit"].median()
print('SALES:',mediana,'QUANTITY:',medianb,'PROFIT:',medianc)
print('Standard Deviation of the given data')
stdeva=df["Sales"].std()
stdevb=df["Quantity"].std()
stdevc=df["Profit"].std()
print('SALES:',stdeva,'QUANTITY:',stdevb,'PROFIT:',stdevc)
print('Variance of the given data')
a=df["Sales"].var()
b=df["Quantity"].var()
c=df["Profit"].var()
print(print('SALES:',a,'QUANTITY:',b,'PROFIT:',c))

#4
#usage of histogram
plt.figure(figsize=(10,6))
sns.histplot(df["Quantity"],bins=20,kde=True)
plt.title("Quantity of Ordered Items")
plt.xlabel("Items quantity")
plt.show()
#usage of bar plot
plt.figure(figsize=(10,6))
plt.bar(df["Product Name"],df["Quantity"],color="g",width=1)
plt.show()
#usage of boxplot
plt.figure(figsize=(8,8))
sns.boxplot(data=df,x='Sales',y='Profit')
plt.show()

#5
a=df.corr()
print(a)

#6
Q1=df.quantile(0.25)
Q3=df.quantile(0.75)
IQR=Q3-Q1
outliers=((df<(Q1-1.5*IQR))|(df>(Q3+1.5*IQR))).sum()
print(outliers)

#7.i
class Walmart:
  def __init__(self,df):
    self.df=df
  def i(self):
    s=df["Sales"]
    p=df["Profit"]
    plt.bar(s,p)
    plt.figure(figsize=[8,8])
  def j(self):
    plt.figure(figsize=(6,8))
    plt.bar(df["Category"],df["Sales"],color="b",width=10)
    plt.show()
  def k(self):
    plt.figure(figsize=(6,8))
    plt.bar(df.groupby('Order ID')df["Order ID"].count(),df["Sales"],color="g",width=10)
    plt.figure(figsize=(12,6))
    plt.show()

a=Walmart(df)
print('trend analysis')
print(a.i())
print(a.j())
print('customer analysis')
print(a.k())

"""TREND ANALYSIS:
 i.Observation of trends between sales and profits defined that there is strong similarity in proportion between them.The sales went high in the middle period and almost similarly profits followed the similar trend.But for the last orders the profit raised.
 ii.Binders,Chairs have shown more profit over the years
CUSTOMER ANALYSIS:
1.CA-2011-106439
2.CA-2012-104346
3.CA-2013-165330
4.CA-2014-117457
5.US-2013-103674
These are the top 5 customers basing on number of orders and total sales

Comprehensive Analysis:
i.The products which are in high demand should be produced more after analysing few factors such as specifically when are they ordered more and at which area and the order trends.
Considering an example of woolen wear,
This will be ordered more in winter,and purchased in more low temperature areas.
Then the sales velocity will be high and the orders should be fulfilled by producing in large scale.


ii.Customers in certain areas are tending to purchase certain products so the distribution should be more towwards that areas which may cause profits for the sales.
For instance,Spices are mostly consumed in asian regions and the supply will be high here instead of the other regions.
So the right good should be supplied in the region.In this way,geography plays a key role

iii.High value customers are the people who are continously engaging in the business and through whom considerable profit is coming.Their loyality plays a significant role in sales.Coupons can be claimed to encourage which wont affect our profit.
Memberships can be introduced inorder to continue them.
"""