# -*- coding: utf-8 -*-
"""python_internal_assessment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yJLnta2P5kwbogylLMkGCigRXFBeVb_J
"""

#1
l=float(input('enter the length of rectangle:'))
w=float(input('enter the width of rectangle:'))
area= l*w
print('area of the rectangle:',area)

#2
weight=(float(input('enter the body weight in kg:')))
height=float(input('enter the height in m^2:'))
BMI=(weight/(height**2))
print('Body Mass Index(kg/m^2):',BMI)

#3
scores_list={}
no_of_students=int(input('no.of students:'))
for i in range (no_of_students):
  name=input('enter the student name:')
  scores=input("enter the student's marks:")
  scores_list[name]=scores
print(scores_list)

#4
age=int(input('enter your age:'))
if age<18:
  print("you're a minor")
elif age>=18 and age<60:
  print("You're an adult")
elif age>=60:
  print("You're a Senior")

#5
for i in range(1,51):
 if i%2==0:
  print(i)

#6
password=input('enter your password:')
confirmation=input('enter again for confirmation:')
while(password!=confirmation):
  print('tryagain')
  confirmation=input('enter again for confirmation:')

#7
def average(a):
  b=a.split()
  sum=0
  for i in range (len(b)):
    sum=sum+b[i]
  avg=sum/len(b)
  return (avg)

  c=int(input('enter the value:'))
  d=c.split()
print(average(c))

#8.
def owels(a):
  b=a.split()
  count=0
  for i in range (len(b)):
    if b[i]== ('a'or 'e' or 'i' or 'o' or 'u' or 'A' or 'E' or 'I' or 'O' or 'U'):
      count=count+1
    else:
      count=count+0
  return count
word=(input('enter the word:'))
print(owels(word))

#9
from datetime import datetime
now=datetime.now()
print(now)

#10
input_1=input('enter the 1st input:')
input_2=input('enter the 2nd input:')
try:
  sum=input_1+input_2
  print(int(sum))
except:
  print("given inputs are non-numeric")

#11
input_1=int(input('enter the integer input:'))
try:
  print(input_1)
except:
  print("value error identified")

#12
input_1=int(input())
input_2=int(input())
try:
 c=input_1/input_2
 print(c)
except:
  print('cannot be divisible by zero')

#13
with open("/content/sample_data/a","w") as file:
  file.write("Hello,Python!")

#14
 with open("/content/sample_data/a","r") as file:
  file.read("Hello,Python!")

#15
with open("/content/sample_data/b","a") as file:
  file.append("Hello,Python!")